In [10]:
import pandas as pd

In [7]:
#Code for creating data frame of testing data
data = pd.read_csv('requests.csv')
data.columns = ['timestamp', 'userID', 'sessionID', 'expiring', 'URL']
print(data)

            timestamp      userID                              sessionID  \
0       1676373343936   user-1003   c85cbd00-d2fc-4cda-9f5c-66616847d851
1       1676373344344   user-1005   a0038f81-b46a-4f26-a7ea-2791d53404fb
2       1676373344456   user-1003   c85cbd00-d2fc-4cda-9f5c-66616847d851
3       1676373344912     user-65   fd48a9f9-67f4-4185-9bcc-a76b7139401c
4       1676373345020   user-1005   a0038f81-b46a-4f26-a7ea-2791d53404fb
...               ...         ...                                    ...
263206  1676444990852    user-629   2a43fe7f-d300-470d-9523-d362b70b37d3
263207  1676444991104    user-629   2a43fe7f-d300-470d-9523-d362b70b37d3
263208  1676444991342    user-629   2a43fe7f-d300-470d-9523-d362b70b37d3
263209  1676444991375   user-1005   0e84ab80-bfa4-402b-9ae0-6397441e91d6
263210  1676444992110   user-1005   0e84ab80-bfa4-402b-9ae0-6397441e91d6

             expiring                            URL
0       1676373495816                 /chat/send/442
1       1676373476316                   /profile/407
2       1676373495816                 /chat/send/969
3       1676373604676            /searchUsers?page=0
4       1676373476316                   /profile/148
...               ...                            ...
263206  1676445248826                   /profile/572
263207  1676445248826              /conversation/572
263208  1676445248826   /conversation/572/markAsRead
263209  1676445040536                   /profile/995
263210  1676445040536                   /profile/380

[263211 rows x 5 columns]

In [12]:
import random

def create_sequence(arr, randVal):
    if (randVal < 1):
        val = random.randint(0,9)
        for i in range (10):
            arr.append(val)
    else:    
        for i in range (0, 10):
            arr.append(i)
    return arr

In [56]:
sequence_matrix = []
for i in range (1000):
    randVal = random.randint(0,9)
    arr = []
    sequence_matrix.append(create_sequence(arr, randVal))

sequence_df = pd.DataFrame(sequence_matrix, columns=['req0', 'req1', 'req2', 'req3', 'req4', 'req5', 'req6', 'req7', 'req8', 'req9'])
sequence_df

     req0  req1  req2  req3  req4  req5  req6  req7  req8  req9
0       0     1     2     3     4     5     6     7     8     9
1       0     1     2     3     4     5     6     7     8     9
2       0     1     2     3     4     5     6     7     8     9
3       0     1     2     3     4     5     6     7     8     9
4       0     1     2     3     4     5     6     7     8     9
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
995     0     1     2     3     4     5     6     7     8     9
996     0     1     2     3     4     5     6     7     8     9
997     0     1     2     3     4     5     6     7     8     9
998     0     0     0     0     0     0     0     0     0     0
999     0     1     2     3     4     5     6     7     8     9

[1000 rows x 10 columns]