In [1]:
import api_files.ml_library as calc
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer

In [26]:
"""Code for fetching the data"""

#Fetch data from csv file
data = calc.read_csv_file('csv_files/requests.csv')

#Extracts a list of all unique users in dataframe
users = calc.extract_users(data)

#Create a datachunk for a spammer
df_chunks = calc.split_user_df(data, users[0]) 
df = df_chunks[0]

In [19]:
from sklearn.feature_extraction.text import HashingVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]
vectorizer = HashingVectorizer(n_features=2**4, norm=None, alternate_sign=False)
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(X.T.todense())
df

      0    1    2    3
0   1.0  2.0  0.0  1.0
1   0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0
4   0.0  0.0  1.0  0.0
5   0.0  0.0  1.0  0.0
6   0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0
8   1.0  0.0  0.0  1.0
9   0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0
11  0.0  1.0  0.0  0.0
12  0.0  0.0  0.0  0.0
13  1.0  1.0  2.0  1.0
14  2.0  2.0  2.0  2.0
15  0.0  0.0  0.0  0.0

In [27]:
#vectorizers
count_vect = CountVectorizer()
Tfidf_vect = TfidfVectorizer()
hash_vect = HashingVectorizer(n_features=100, norm=None, alternate_sign=False)

#cleaning data and fit the vectorizers
clean_data = calc.clean_reqlogs(data)
count_vect = count_vect.fit(clean_data['request_logs'])
Tfidf_vect = Tfidf_vect.fit(clean_data['request_logs'])

#clean data chunk that will be transformed by the vectorizers
cleaned = calc.clean_reqlogs(df)
result_count = count_vect.transform(cleaned['request_logs'])
result_tfidf = Tfidf_vect.transform(cleaned['request_logs'])
result_hash = hash_vect.fit_transform(cleaned['request_logs'])

In [7]:
cleaned['request_logs']

 user-1003     /chat/send/  /chat/send/  /searchusers?page= ...
Name: request_logs, dtype: object

In [28]:
#HashVectorizer for user-1003 (spammer)
df = pd.DataFrame(result_hash.T.todense(), columns=["hash"])
df.sort_values(by=["hash"],ascending=False)

    hash
29  37.0
19  37.0
49  13.0
89  13.0
0    0.0
..   ...
32   0.0
31   0.0
30   0.0
28   0.0
99   0.0

[100 rows x 1 columns]

In [5]:
#CountVectorizer for user-1003 (spammer)
df = pd.DataFrame(result_count.T.todense(), index=count_vect.get_feature_names_out(), columns=["count"])
df.sort_values(by=["count"],ascending=False)

              count
chat             40
send             40
page             15
searchusers      15
block             0
config            0
conversation      0
inbox             0
like              0
login             0
markasread        0
photos            0
profile           0
report            0
userconfig        0

In [6]:
#TfidfVectorizer for user-1003 (spammer)
df = pd.DataFrame(result_tfidf.T.todense(), index=Tfidf_vect.get_feature_names_out(), columns=["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

                 tfidf
chat          0.662166
send          0.662166
page          0.248065
searchusers   0.248065
block         0.000000
config        0.000000
conversation  0.000000
inbox         0.000000
like          0.000000
login         0.000000
markasread    0.000000
photos        0.000000
profile       0.000000
report        0.000000
userconfig    0.000000

In [ ]:
#Code for extracting a normal user
df_chunks = calc.split_user_df(data, users[10]) 
df = df_chunks[0]

#clean data chunk that will be transformed by the vectorizers
cleaned = calc.clean_reqlogs(df)
result_count = count_vect.transform(cleaned['request_logs'])
result_tfidf = Tfidf_vect.transform(cleaned['request_logs'])

In [8]:
#CountVectorizer for user-499 (normal)
df = pd.DataFrame(result_count.T.todense(), index=count_vect.get_feature_names_out(), columns=["count"])
df.sort_values(by=["count"],ascending=False)

              count
conversation     16
profile          14
page             10
markasread        8
searchusers       6
chat              5
send              5
inbox             4
login             4
block             1
report            1
config            0
like              0
photos            0
userconfig        0

In [10]:
#TfidfVectorizer for user-499 (normal)
df = pd.DataFrame(result_tfidf.T.todense(), index=Tfidf_vect.get_feature_names_out(), columns=["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

                 tfidf
conversation  0.588897
profile       0.514772
page          0.366963
markasread    0.294448
searchusers   0.220178
chat          0.183664
send          0.183664
inbox         0.159757
login         0.146785
report        0.046614
block         0.040787
config        0.000000
like          0.000000
photos        0.000000
userconfig    0.000000